### ISSUE TITLE
Adopting project Code of Conduct

### ISSUE THREAD

**Issue by gdcutting** [occam-ra/occam#17]
We have had spirited discussion on the code of conduct issue. After some discussion, we have decided to adopt a slightly modified version of the Contributor Covenant, as follows:

![image](https://user-images.githubusercontent.com/24381091/52446367-a9b99c80-2ae2-11e9-9d70-af5a305fc6c6.png)

Final discussion and adoption is on the agenda for the Friday 2/8 developer meeting.

**Comment by Gooseus** [comment]
This Code of Conduct was accepted at the meeting on Feb 8th by all attending members of the project.

**Comment by gdcutting** [comment]
CoC adopted at meeting. Document posted with very minor markdown changes for formatting. Closing issue.
