### ISSUE TITLE
Take PSU-branded stuff out of web front pages.

### ISSUE THREAD

**Issue by gdcutting** [occam-ra/occam#5]
Currently there is some Portland State branding in the front (HTML) files. Go through and figure out how to take this out so we're no longer enforcing the appearance from dmm.sysc.pdx.edu.

**Comment by Gooseus** [comment]
I think this may be wrapped up in a greater issue of replacing the web interface altogether.

I'm not sure where that would be on the project roadmap or if we'd want to remove branding sooner as an isolated task?

**Comment by BartMassey** [comment]
Remove the branding first, I think. PSU will get really antsy if they find out we've been distributing their branding. Also it's a great opportunity to advertise OCCAM per se with a generic OCCAM frontend that many folks won't bother to replace.

**Comment by Gooseus** [comment]
@gdcutting What isn't fixed?

**Comment by gdcutting** [comment]
Just seemed like changes you made to  gooseus/remove-psu had not yet been merged upstream into main repo. Like if someone installed from occam-ra/occam master they would still get the PSU stuff.

**Comment by gdcutting** [comment]
I was just still seeing PSU-related mentions in the HTML/css but realized the visual is fine now because the PSU header image is gone. Will need a little more further cleanup at some point probably but can close for now. Thanks
