### ISSUE TITLE
compile error with latest code base

### ISSUE THREAD

**Issue by pramod2804** [occam-ra/occam#64]
Hello, I'm getting an error in one of the cpp file ( Report.cpp) I was wondering if anyone knows how to fix it. 
![image](https://user-images.githubusercontent.com/6914504/222014369-ac5f21fb-76d3-4b3f-a9d2-1ebc3d6641a9.png)

**Comment by BartMassey** [comment]
At line 27 change `int` to `Direction`. At line 535 change `dv_target` to `*dv_target`, probably.

**Comment by BartMassey** [comment]
I think PR #65 closes this issue when merged.

**Comment by bowertree** [comment]
Fixed in merged PR #65
